### PR TITLE
Release notes

### PR DESCRIPTION
**Pull request by IOB1979**

### CODE REVIEW

**Comment by ecaron** [comment]
+1

**Comment by leahdebruycker** [comment]
I get an error when building this: "First line of 2016-01-01_R16-1.md does not match appropriate format" Please verify the format is correct.

**Comment by IOB1979** [comment]
I'm not sure what wasn't working in the first line, but I re-entered it.

**Comment by leahdebruycker** [comment]
Everything looked good this time when I pulled the files down to build them.

**Pull request merged**
